# Specify a base image
FROM  node:alpine

WORKDIR /usr/app

# Install some depenendencies
COPY ./package.json ./
RUN npm config set strict-ssl false
RUN npm install
COPY ./ ./ 

# Default command
CMD ["npm", "run", "start"]